### ISSUE TITLE
Unable to fetch the Music

### ISSUE THREAD

**Issue by chamodlakmal** [15Dkatz/spotify-api-wrapper#2]
Hi,
I am getting errors while fetching music. The error message says that "Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds."

Any help would be appreciated.

**Comment by hector-yaque-telus** [comment]
I think so that happen because the server is down and not longer available. Now I'm trying to run the project locally but I couldn't.

**Comment by hector-yaque-telus** [comment]
You can run the project locally and instead of call https://spotify-api-wrapper.appspot.com/artist/bruno do a local call http://localhost:3000/artist/bruno.

What you need to do
1. Follow the guide https://developer.spotify.com/documentation/general/guides/authorization/app-settings/  to create your Client ID and Client Secret, you can use a free Spotify account.
2. Clone the code of this project, then create this file `secrets/spotify-credentials.json` with this content
```
{
    "id":"HERE_YOU_CLIENT_ID",
    "secret":"HERE_YOU_CLIENT_SECRET"
}
```
3. Run the project with `npm run dev`
4. Try to do this request http://localhost:3000/artist/bruno.

**Comment by joeohm** [comment]
Thank you hector-yaque-telus for the instructions, it worked for me.

**Comment by 15Dkatz** [comment]
I have the api up and running. Thanks for the thread!
